/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ShippingDto } from '../../models/shipping-dto';

export interface GetShippingsByStatus$Params {
  status: string;
}

export function getShippingsByStatus(http: HttpClient, rootUrl: string, params: GetShippingsByStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ShippingDto>>> {
  const rb = new RequestBuilder(rootUrl, getShippingsByStatus.PATH, 'get');
  if (params) {
    rb.path('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ShippingDto>>;
    })
  );
}

getShippingsByStatus.PATH = '/api/shipping/status/{status}';
