/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ShippingDto } from '../../models/shipping-dto';

export interface TrackShipping$Params {
  trackingNumber: string;
}

export function trackShipping(http: HttpClient, rootUrl: string, params: TrackShipping$Params, context?: HttpContext): Observable<StrictHttpResponse<ShippingDto>> {
  const rb = new RequestBuilder(rootUrl, trackShipping.PATH, 'get');
  if (params) {
    rb.path('trackingNumber', params.trackingNumber, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ShippingDto>;
    })
  );
}

trackShipping.PATH = '/api/shipping/track/{trackingNumber}';
