/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ShippingDto } from '../../models/shipping-dto';
import { ShippingStatusUpdateRequest } from '../../models/shipping-status-update-request';

export interface UpdateShippingStatus$Params {
  trackingNumber: string;
      body: ShippingStatusUpdateRequest
}

export function updateShippingStatus(http: HttpClient, rootUrl: string, params: UpdateShippingStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<ShippingDto>> {
  const rb = new RequestBuilder(rootUrl, updateShippingStatus.PATH, 'patch');
  if (params) {
    rb.path('trackingNumber', params.trackingNumber, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ShippingDto>;
    })
  );
}

updateShippingStatus.PATH = '/api/shipping/track/{trackingNumber}/status';
