export interface CityData {
  city: string;
  province: string;
}

export const TUNISIA_CITIES: CityData[] = [
  { city: 'Tunis', province: 'Tunis' },
  { city: 'Sfax', province: 'Sfax' },
  { city: 'Sousse', province: 'Sousse' },
  { city: 'Kairouan', province: 'Kairouan' },
  { city: 'Kébili', province: 'Kébili' },
  { city: 'Bizerte', province: 'Bizerte' },
  { city: 'Sakiet ed Daier', province: 'Sfax' },
  { city: 'Gabès', province: 'Gabès' },
  { city: 'Ariana', province: 'L\'Ariana' },
  { city: 'Jendouba', province: 'Jendouba' },
  { city: 'Gafsa', province: 'Gafsa' },
  { city: 'Medenine', province: 'Médenine' },
  { city: 'Béja', province: 'Béja' },
  { city: 'Kasserine', province: 'Kasserine' },
  { city: 'Monastir', province: 'Monastir' },
  { city: 'Radès', province: 'Ben Arous' },
  { city: 'Hammamet', province: 'Nabeul' },
  { city: 'Tataouine', province: 'Tataouine' },
  { city: 'La Marsa', province: 'Tunis' },
  { city: 'Ben Arous', province: 'Ben Arous' },
  { city: 'Sakiet ez Zit', province: 'Sfax' },
  { city: 'Zarzis', province: 'Médenine' },
  { city: 'Ben Gardane', province: 'Médenine' },
  { city: 'Mahdia', province: 'Mahdia' },
  { city: 'Houmt Souk', province: 'Médenine' },
  { city: 'Feriana', province: 'Kasserine' },
  { city: 'Fouchana', province: 'Ben Arous' },
  { city: 'Le Kram', province: 'Tunis' },
  { city: 'El Kef', province: 'Kef' },
  { city: 'El Hamma', province: 'Gabès' },
  { city: 'Nabeul', province: 'Nabeul' },
  { city: 'Le Bardo', province: 'Tunis' },
  { city: 'Korba', province: 'Nabeul' },
  { city: 'Oued Lill', province: 'Manouba' },
  { city: 'Menzel Temime', province: 'Nabeul' },
  { city: 'Ghardimaou', province: 'Jendouba' },
  { city: 'Midoun', province: 'Médenine' },
  { city: 'Kelaa Kebira', province: 'Sousse' },
  { city: 'Moknine', province: 'Monastir' },
  { city: 'Menzel Bourguiba', province: 'Bizerte' },
  { city: 'Manouba', province: 'Manouba' },
  { city: 'Kélibia', province: 'Nabeul' },
  { city: 'Rass el Djebel', province: 'Bizerte' },
  { city: 'Ksour Essaf', province: 'Mahdia' },
  { city: 'Bir Ali Ben Khalifa', province: 'Sfax' },
  { city: 'Sidi Bouzid', province: 'Sidi Bouzid' },
  { city: 'El Jem', province: 'Mahdia' },
  { city: 'Tebourba', province: 'Manouba' },
  { city: 'Ksar Hellal', province: 'Monastir' },
  { city: 'Douz', province: 'Kébili' },
  { city: 'La Goulette', province: 'Tunis' },
  { city: 'Jedeïda', province: 'Manouba' },
  { city: 'Hammam Sousse', province: 'Sousse' },
  { city: 'Hammam-Lif', province: 'Ben Arous' },
  { city: 'Metlaoui', province: 'Gafsa' },
  { city: 'Tozeur', province: 'Tozeur' },
  { city: 'Siliana', province: 'Siliana' },
  { city: 'Dar Chabanne', province: 'Nabeul' },
  { city: 'Aïne Draham', province: 'Jendouba' },
  { city: 'Ez Zahra', province: 'Ben Arous' },
  { city: 'Thala', province: 'Kasserine' },
  { city: 'Mateur', province: 'Bizerte' },
  { city: 'Beni Khiar', province: 'Nabeul' },
  { city: 'Rhennouch', province: 'Gabès' },
  { city: 'Dahmani', province: 'Kef' },
  { city: 'Grombalia', province: 'Nabeul' },
  { city: 'El Alia', province: 'Bizerte' },
  { city: 'Ar Rudayyif', province: 'Gafsa' },
  { city: 'Mégrine', province: 'Ben Arous' },
  { city: 'El Fahs', province: 'Zaghouan' },
  { city: 'Zaouiet Sousse', province: 'Sousse' },
  { city: 'Chebba', province: 'Mahdia' },
  { city: 'Ajim', province: 'Médenine' },
  { city: 'Takelsa', province: 'Nabeul' },
  { city: 'Medjez el Bab', province: 'Béja' },
  { city: 'El Maknassi', province: 'Sidi Bouzid' },
  { city: 'Beni Khalled', province: 'Nabeul' },
  { city: 'La Mornaghia', province: 'Manouba' },
  { city: 'Ouardenine', province: 'Monastir' },
  { city: 'Moularès', province: 'Gafsa' },
  { city: 'Nefta', province: 'Tozeur' },
  { city: 'Sahline', province: 'Monastir' },
  { city: 'Carthage', province: 'Tunis' },
  { city: 'Tinja', province: 'Bizerte' },
  { city: 'Tabursuq', province: 'Béja' },
  { city: 'Zaghouan', province: 'Zaghouan' },
  { city: 'Sbeitla', province: 'Kasserine' },
  { city: 'Rhar el Melah', province: 'Bizerte' },
  { city: 'Tajerouine', province: 'Kef' },
  { city: 'Menzel Abderhaman', province: 'Bizerte' },
  { city: 'Mennzel Bou Zelfa', province: 'Nabeul' },
  { city: 'Galaat el Andeless', province: 'L\'Ariana' },
  { city: 'Banbalah', province: 'Monastir' },
  { city: 'Bekalta', province: 'Monastir' },
  { city: 'Tabarka', province: 'Jendouba' },
  { city: 'Mareth', province: 'Gabès' },
  { city: 'Wadhraf', province: 'Gabès' },
  { city: 'Ghomrassen', province: 'Tataouine' },
  { city: 'Mahires', province: 'Sfax' },
  { city: 'Bennane', province: 'Monastir' },
  { city: 'Goubellat', province: 'Béja' },
  { city: 'Gammarth', province: 'Tunis' },
  { city: 'Ksibet el Mediouni', province: 'Monastir' },
  { city: 'El Guetar', province: 'Gafsa' },
  { city: 'Messadine', province: 'Sousse' },
  { city: 'Bir M\'cherga', province: 'Zaghouan' },
  { city: 'Hammam el Rhezez', province: 'Nabeul' },
  { city: 'Testour', province: 'Béja' },
  { city: 'Bou Arada', province: 'Siliana' },
  { city: 'Maktar', province: 'Siliana' },
  { city: 'M\'dhilla', province: 'Gafsa' },
  { city: 'Seïada', province: 'Monastir' },
  { city: 'Bou Arkoub', province: 'Nabeul' },
  { city: 'As Sars', province: 'Kef' },
  { city: 'Zriba-Village', province: 'Nabeul' },
  { city: 'Bou Merdès', province: 'Mahdia' },
  { city: 'Agareb', province: 'Sfax' },
  { city: 'Er Regueb', province: 'Sidi Bouzid' },
  { city: 'Rejiche', province: 'Mahdia' },
  { city: 'Sidi Tabet', province: 'L\'Ariana' },
  { city: 'Enfida', province: 'Sousse' },
  { city: 'Ousseltia', province: 'Kairouan' },
  { city: 'Hajeb el Aïoun', province: 'Kairouan' },
  { city: 'Sidi Bou Ali', province: 'Sousse' },
  { city: 'Gafour', province: 'Siliana' },
  { city: 'Remada', province: 'Tataouine' },
  { city: 'Khunays', province: 'Monastir' },
  { city: 'Jerissa', province: 'Kef' },
  { city: 'El Haouaria', province: 'Nabeul' },
  { city: 'Menzel Kamel', province: 'Monastir' },
  { city: 'Tazarka', province: 'Nabeul' },
  { city: 'Harqalah', province: 'Sousse' },
  { city: 'Beni Hassane', province: 'Monastir' },
  { city: 'Haffouz', province: 'Kairouan' },
  { city: 'Khledia', province: 'Ben Arous' },
  { city: 'El Maamoura', province: 'Nabeul' },
  { city: 'Degache', province: 'Tozeur' },
  { city: 'Zaouiat Djedidi', province: 'Nabeul' },
  { city: 'Sidi Alouane', province: 'Mahdia' },
  { city: 'Hencha', province: 'Sfax' },
  { city: 'El Metline', province: 'Bizerte' },
  { city: 'Touza', province: 'Monastir' },
  { city: 'Djebeniana', province: 'Sfax' },
  { city: 'Es Somaa', province: 'Nabeul' },
  { city: 'Melloulèche', province: 'Mahdia' },
  { city: 'Zaouiet Kountech', province: 'Monastir' },
  { city: 'Bir el Hafey', province: 'Sidi Bouzid' },
  { city: 'Bodeur', province: 'Monastir' },
  { city: 'Borj Mejen Bel Abbès', province: 'Kasserine' },
  { city: 'El Battan', province: 'Manouba' },
  { city: 'Sakiet Sidi Youssef', province: 'Kef' },
  { city: 'Lemta', province: 'Monastir' },
  { city: 'Sidi Bou Saïd', province: 'Tunis' },
  { city: 'Nibbar', province: 'Kef' },
  { city: 'Menzel Heurr', province: 'Nabeul' },
  { city: 'Mesdour', province: 'Monastir' },
  { city: 'Fernana', province: 'Jendouba' },
  { city: 'Souassi', province: 'Mahdia' },
  { city: 'Sidi Ben Nour', province: 'Monastir' },
  { city: 'Dehiba', province: 'Tataouine' },
  { city: 'El Mida', province: 'Nabeul' },
  { city: 'Tourki', province: 'Nabeul' },
  { city: 'Korbous', province: 'Nabeul' },
  { city: 'Salakta', province: 'Mahdia' },
  { city: 'Beni Kheddache', province: 'Médenine' },
  { city: 'El Aroussa', province: 'Siliana' },
  { city: 'Er-Remla', province: 'Sfax' },
];