/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubscriberDto } from '../../models/subscriber-dto';

export interface GetAllActiveSubscribers$Params {
}

export function getAllActiveSubscribers(http: HttpClient, rootUrl: string, params?: GetAllActiveSubscribers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SubscriberDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllActiveSubscribers.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SubscriberDto>>;
    })
  );
}

getAllActiveSubscribers.PATH = '/api/subscribers';
