/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubscriberDto } from '../../models/subscriber-dto';

export interface Subscribe$Params {
      body: SubscriberDto
}

export function subscribe(http: HttpClient, rootUrl: string, params: Subscribe$Params, context?: HttpContext): Observable<StrictHttpResponse<SubscriberDto>> {
  const rb = new RequestBuilder(rootUrl, subscribe.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SubscriberDto>;
    })
  );
}

subscribe.PATH = '/api/subscribers';
