/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type DiscountType = 'FIXED' | 'PERCENTAGE';

export interface CreateDiscountCodeRequest {
  userPrefix: string;
  discountType: DiscountType;
  discountValue: number;
  minimumOrderAmount?: number;
  maxUses?: number;
  maxUsesPerCustomer?: number;
  expiresAt?: string;
}