/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type DiscountType = 'FIXED' | 'PERCENTAGE';

export interface DiscountCode {
  id?: number;
  code?: string;
  userPrefix?: string;
  discountType?: DiscountType;
  discountValue?: number;
  minimumOrderAmount?: number;
  maxUses?: number;
  currentUses?: number;
  maxUsesPerCustomer?: number;
  expiresAt?: string;
  active?: boolean;
  createdAt?: string;
  updatedAt?: string;
}