/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InventoryDto {
  availableQuantity?: number;
  inStock?: boolean;
  lowStock?: boolean;
  quantity?: number;
}
