/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderItemDto {
  productId?: number;
  productName?: string;
  quantity?: number;
  totalPrice?: number;
  unitPrice?: number;
}
