/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ShippingStatusDto {
  createdAt?: string;
  description?: string;
  id?: number;
  location: string;
  notes?: string;
  shippingId: number;
  status: string;
  timestamp: string;
  updatedBy?: string;
}
