/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ShippingStatusUpdateRequest {
  description?: string;
  location: string;
  notes?: string;
  status: string;
  updatedBy?: string;
}
