/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddressDto } from '../../models/address-dto';

export interface GetCustomerAddressesByType$Params {
  email: string;
  type: string;
}

export function getCustomerAddressesByType(http: HttpClient, rootUrl: string, params: GetCustomerAddressesByType$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AddressDto>>> {
  const rb = new RequestBuilder(rootUrl, getCustomerAddressesByType.PATH, 'get');
  if (params) {
    rb.path('email', params.email, {});
    rb.path('type', params.type, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AddressDto>>;
    })
  );
}

getCustomerAddressesByType.PATH = '/api/addresses/customer/{email}/type/{type}';
