/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddressDto } from '../../models/address-dto';

export interface SetDefaultAddress$Params {
  id: number;
  customerEmail: string;
}

export function setDefaultAddress(http: HttpClient, rootUrl: string, params: SetDefaultAddress$Params, context?: HttpContext): Observable<StrictHttpResponse<AddressDto>> {
  const rb = new RequestBuilder(rootUrl, setDefaultAddress.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('customerEmail', params.customerEmail, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AddressDto>;
    })
  );
}

setDefaultAddress.PATH = '/api/addresses/{id}/set-default';
